export const toolTipObj = {
  Bronze: {
    Basic: "Basic coverage tailored to the vehicle's standard",
    Basic: "Basic customer service during business hours",
    "100 Miles": "Fuel allowance of 100 daily miles",
    Basic: "Standard assistance in case of breakdowns within a limited range.",
    Standard: "Standard cancellation policy with limited flexibility",
    "": null,
    Concierge: null,
    "Car Swap": null,
    "Future Discount": null,
    "Additional Perks": null,
    Pricing: null,
  },
  Silver: {
    Enhanced: "Enhanced coverage with lower deductibles and broader protection",
    Priority: "Dedicated support line with extended hours",
    "200 Miles": "Enhanced fuel allowance of 200 daily miles",
    Extended:
      "Broader coverage and fast response times of guaranteed 60 minute recovery",
    "Flexi Plus(+)": "Improved flexibility with cancellation policies",
    "(within 150 Miles)": "Within 150 miles",
    Concierge: null,
    "Car Swap": null,
    "Future Discount": null,
    "Additional Perks": null,
    Pricing: null,
  },
  Gold: {
    Comprehensive: "Comprehensive coverage, minimal or no deductibles",
    "Dedicated Agent":
      "Personalized service representative throughout the rental period",
    "400 Miles": "Incredible fuel allowance of 400 daily miles",
    Full: "Comprehensive coverage, including longer-range assistance and guaranteed 30 minute recovery",
    "Flexi Pro(++)": "Most flexible cancellation policies available",
    "(within 400 Miles)": "Within 400 miles",
    Concierge: null,
    "Car Swap": null,
    "Future Discount": null,
    "Additional Perks": null,
    Pricing: null,
  },
};
