export const toolTipObj = {
  Tarriff: {
    "Insurance Package": "Insurance Package",
    "Customer Support": "Customer Support",
    "Mileage Allowance": "Allocated Fuel",
    "Roadside Assistance": "Roadside Assistance",
    Cancellation: "Cancellation",
    "Pickup/Delivery": "Pickup",
    Concierge: "Concierge",
    "Car Swap": "Car Swap",
    "Future Discount": "Future Discount",
    "Additional Perks": "Additional Perks",
    Pricing: "Pricing",
  },
  Bronze: {
    Basic: "Basic Insurance",
    "Basic ": "Basic Customer Support",
    "100 Miles": "100 miles from Pickup",
    "Basic  ": "Basic Roadside assistance",
    Standard: "No cancellation",
  },
  Silver: {
    Enhanced: "",
    Priority: "",
    "200 Miles": "",
    Extended: "",
    "Flexi Plus(+)": "",
    "Within 150 miles": "15",
  },
  Gold: {
    Comprehensive: "",
    "Dedicated Agent": "",
    "400 Miles": "",
    Full: "",
    "Flexi Pro(++)": "",
    "Within 400 miles": "wooo",
  },
};
